#!/bin/sh
# -----------------------------------------------------------------------------
# Copyright 2005 Open Source Applications Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper script for Tomcat's catalina.sh that sets up the environment
# and changes the directory to run in the Cosmo distribution directory.
#
# Ripped off from Tomcat's shutdown.sh
# -----------------------------------------------------------------------------

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

RECOVERY_DIR=`dirname "$PRG"`
SQLTOOL_RC="$RECOVERY_DIR/sqltool.rc"

COSMO_HOME=`pwd`

USERFILE="cosmo-homedir-recovery-users.txt"

if [ ! -d "$COSMO_HOME"/data ]; then
    echo "This script must be run in the Cosmo installation directory."
    exit 1
fi
if [ ! -d "$COSMO_HOME"/tomcat ]; then
    echo "This script must be run in the Cosmo installation directory."
    exit 1
fi

java -jar tomcat/common/lib/hsqldb-1.7.3.3.jar \
    --rcfile "$SQLTOOL_RC" --noinput --sql 'select username from user;' \
    cosmo-0.2 > "$USERFILE"

CLASSPATH="$RECOVERY_DIR/target/homedir-recovery-0.2.6-1.jar;tomcat/common/lib/commons-logging-1.0.4.jar"

java -cp $CLASSPATH org.osaf.cosmo.ops.HomeDirectoryRecoverer "$USERFILE"
